# Site settings
title: Frank Hsu's Website
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "FrankHsu327.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Frank Hsu
user_description: I am an electrical engineering student at UNSW. I studied in mechanical engineering for my bachelor degree at NTHU in Taiwan. However, I found my passion in circuit design and embedded system developement during the period. I've participated in a Formula stduent team, which gave me opportunity to design and manufacture PCB of the battery management system. This experience motivated me to study on electronics, embedded system and further knowledge.
user_title: Welcome to my website
email: frank.hsu327@gmail.com
# twitter_username: lorem_ipsum
instagram_username: chenghuanx?igshid=YmMyMTA2M2Y=
facebook_username: chenghuanx
linkedin_username: frank-hsu-76abb31b6
github_username:  FrankHsu327
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
