# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "FrankHsu327.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: frank.hsu327@gmail.com
# twitter_username: lorem_ipsum
instagram_username: chenghuanx?igshid=YmMyMTA2M2Y=
facebook_username: chenghuanx
linkedin_username: frank-hsu-76abb31b6
github_username:  FrankHsu327
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
